-- PROCEDURE: public.add_crash(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, bigint)

-- DROP PROCEDURE IF EXISTS public.add_crash(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, bigint);

CREATE OR REPLACE PROCEDURE public.add_crash(
	_crash_key text,
	_city text,
	_drivers_license_class text,
	_drivers_license_restrictions text,
	_drivers_license_state text,
	_commercial_drivers_license text,
	_age text,
	_vehicle_seizure text,
	_alcohol_suspected text,
	_alcohol_test text,
	_alcohol_result_type text,
	_airbag_switch text,
	_airbag_deployed text,
	_ejection text,
	_gender text,
	_race text,
	_injury text,
	_protection text,
	_trapped text,
	_person_type text,
	_vision_obstruction text,
	_contributing_circumstance_1 text,
	_contributing_circumstance_2 text,
	_contributing_circumstance_3 text,
	_vehicletype text,
	_date_of_crash bigint)
LANGUAGE 'sql'
AS $BODY$
INSERT INTO public.crash(
	crash_key, 
	city, 
	drivers_license_class, 
    drivers_license_restrictions, 
    drivers_license_state, 
    commercial_drivers_license, 
    age, 
    vehicle_seizure, 
    alcohol_suspected, 
    alcohol_test, 
    alcohol_result_type, 
    airbag_switch, 
    airbag_deployed, 
    ejection, 
    gender, 
    race, 
    injury, 
    protection, 
    trapped, 
    person_type, 
    vision_obstruction, 
    contributing_circumstance_1, 
    contributing_circumstance_2, 
    contributing_circumstance_3, 
    vehicletype, 
    date_of_crash
    ) VALUES (
    _crash_key,
	_city,
	_drivers_license_class,
    _drivers_license_restrictions,
    _drivers_license_state,
    _commercial_drivers_license, 
    _age,
    _vehicle_seizure,
    _alcohol_suspected,
    _alcohol_test,
    _alcohol_result_type,
    _airbag_switch,
    _airbag_deployed,
    _ejection,
    _gender,
    _race,
    _injury,
    _protection,
    _trapped,
    _person_type,
    _vision_obstruction, 
    _contributing_circumstance_1,
    _contributing_circumstance_2,
    _contributing_circumstance_3,
    _vehicletype,
    _date_of_crash
        )
		ON CONFLICT (crash_key) DO NOTHING;
$BODY$;
